<?php

namespace App\Http\Controllers\HRMS\EmployeDetails;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Exports\GeneralReportExport;
use Maatwebsite\Excel\Facades\Excel;

class EmployeExportController extends Controller
{
    // public function exportEmployees()
    // {
    //     $data = DB::connection('sqlsrv2')->table('Emp_Profile')
    //         ->join('Emp_Register', 'Emp_Profile.EmployeeID', '=', 'Emp_Register.EmployeeID')
    //         ->select(
    //             'Emp_Profile.Name',
    //             'Emp_Profile.FatherHusband',
    //             'Emp_Profile.Email',
    //             'Emp_Profile.Mobile',
    //             'Emp_Profile.CNIC',
    //             'Emp_Profile.DOB',
    //             'Emp_Register.Department',
    //             'Emp_Register.Designation',
    //             'Emp_Register.JoiningDate',
    //         )
    //         ->get()
    //         ->map(function ($item) {
    //             return [
    //                 $item->Name,
    //                 $item->FatherHusband,
    //                 $item->Email,
    //                 $item->Mobile,
    //                 $item->CNIC,
    //                 $item->DOB,
    //                 $item->Department,
    //                 $item->Designation,
    //                 $item->JoiningDate,
    //             ];
    //         });

    //     $headings = [
    //         'Name',
    //         'Father/Husband',
    //         'Email',
    //         'Mobile',
    //         'CNIC',
    //         'DOB',
    //         'Department',
    //         'Designation',
    //         'Joining Date'
    //     ];

    //     $additionalFields = [
    //         'Report Title' => 'Employee Export',
    //         'Date' => now()->format('d-m-Y H:i'),
    //         'Generated By' => auth()->user()->name ?? 'System'
    //     ];

    //     return Excel::download(new GeneralReportExport($data, $headings, $additionalFields), 'employee_export.xlsx');
    // }
    public function exportEmployees()
    {
        $data = DB::connection('sqlsrv2')->table('Emp_Profile')
            ->join('Emp_Register', 'Emp_Profile.EmployeeID', '=', 'Emp_Register.EmployeeID')
            ->select('Emp_Profile.*', 'Emp_Register.*')
            ->get()
            ->map(function ($item) {
                return (array) $item;
            });

        $headings = array_keys((array) $data->first());

        $additionalFields = [
            'Report Title' => 'Employee Full Export',
            'Date' => now()->format('d-m-Y H:i'),
            'Generated By' => auth()->user()->name ?? 'System'
        ];

        return Excel::download(new GeneralReportExport($data, $headings, $additionalFields), 'employee_full_export.xlsx');
    }
    // public function exportEmployees()
    // {
    //     $data = DB::connection('sqlsrv2')
    //         ->table('Emp_Profile')
    //         ->get()
    //         ->map(function ($item) {
    //             return (array) $item;
    //         });

    //     $headings = array_keys((array) $data->first());

    //     $additionalFields = [
    //         'Report Title'  => 'Employee Profile Export',
    //         'Date'          => now()->format('d-m-Y H:i'),
    //         'Generated By'  => auth()->user()->name ?? 'System'
    //     ];

    //     return Excel::download(
    //         new GeneralReportExport($data, $headings, $additionalFields),
    //         'employee_profile_export.xlsx'
    //     );
    // }
    public function exportRegisteredEmployees()
    {
        $data = DB::connection('sqlsrv2')
            ->table('Emp_Register')
            ->get()
            ->map(function ($item) {
                return (array) $item;
            });

        $headings = array_keys((array) $data->first());

        $additionalFields = [
            'Report Title'  => 'Employee Register Export',
            'Date'          => now()->format('d-m-Y H:i'),
            'Generated By'  => auth()->user()->name ?? 'System'
        ];

        return Excel::download(
            new GeneralReportExport($data, $headings, $additionalFields),
            'employee_register_export.xlsx'
        );
    }
}
